name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push user-app Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user-app
          push: true
          tags: faizanx168/gopay-user-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Build and Push bank-webhook Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.bankhook
          push: true
          tags: faizanx168/gopay-bank-webhook:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Build and Push q-worker Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.qworker
          push: true
          tags: faizanx168/gopay-q-worker:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Verify Pushed Images
        run: |
          docker pull faizanx168/gopay-user-app:latest
          docker pull faizanx168/gopay-bank-webhook:latest
          docker pull faizanx168/gopay-q-worker:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull Docker images
            sudo docker pull faizanx168/gopay-user-app:latest
            sudo docker pull faizanx168/gopay-bank-webhook:latest
            sudo docker pull faizanx168/gopay-q-worker:latest

            # Stop and remove existing containers
            sudo docker stop gopay-user-app gopay-bank-webhook gopay-q-worker || true
            sudo docker rm gopay-user-app gopay-bank-webhook gopay-q-worker || true

            # Run Redis container
            sudo docker run -d --name redis -p 6379:6379 redis

            # Run new containers with environment variables
            sudo docker run -d \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
              --name gopay-user-app \
              -p 3000:3000 \
              faizanx168/gopay-user-app:latest
              
            sudo docker run -d \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              --name gopay-bank-webhook \
              -p 3001:3001 \
              faizanx168/gopay-bank-webhook:latest
              
            sudo docker run -d \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e REDIS_URL=redis://redis:6379 \
              --name gopay-q-worker \
              -p 3002:3002 \
              faizanx168/gopay-q-worker:latest

      - name: Notify on Success
        if: success()
        run: echo "Deployment succeeded!"

      - name: Notify on Failure
        if: failure()
        run: echo "Deployment failed!"
